version: "3.8"
services:
    postgres:
        image: postgres
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
    prisma:
        image: prismagraphql/prisma
        environment:
            DATABASE_URL: postgresql://postgres:postgres@postgres/mydb
        ports:
            - "4466:4466"
        volumes:
            - prisma_data:/app/prisma
        depends_on:
            - postgres
volumes:
    postgres_data:
    prisma_data:
